# share.ps1 - The "Active Worker" Build Server

# 0. Check Dependencies (Lazy Load)
$forceInstall = $args -contains "--force"
$reqHash = Get-FileHash -Path "requirements.txt" | Select-Object -ExpandProperty Hash
$hashFile = Join-Path $env:TEMP "babel_req_hash.txt"
$lastHash = if (Test-Path $hashFile) { Get-Content $hashFile } else { "" }

if ($forceInstall -or ($reqHash -ne $lastHash)) {
    Write-Host "Syncing dependencies..." -ForegroundColor Cyan
    pip install -r requirements.txt --quiet
    $reqHash | Out-File $hashFile
} else {
    Write-Host "Dependencies in sync (use --force to update)." -ForegroundColor Gray
}

# 1. Start UI build watcher
Write-Host "Launching UI Watcher..." -ForegroundColor Cyan
Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd ui; npm run build -- --watch"

# 2. Start the Backend server
Write-Host "Launching Backend Server..." -ForegroundColor Green
$env:SHARE_MODE = "1"
# Note: SHARE_PASSWORD is auto-generated by server/app.py if not set
Start-Process powershell -ArgumentList "-NoExit", "-Command", "python -m uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload-exclude '*.log' --reload-exclude '*.db*' --reload-exclude '_*.py' --reload-exclude 'runner_live.log'"

# 3. Start the Tunnel
Write-Host "Establishing Localtunnel connection..." -ForegroundColor Yellow
$ltProcess = Start-Process npx -ArgumentList "localtunnel --port 8000" -PassThru -NoNewWindow -RedirectStandardOutput "lt_out.txt"

$attempts = 0
$url = ""
while ($attempts -lt 10 -and -not $url) {
    Start-Sleep -Seconds 2
    if (Test-Path "lt_out.txt") {
        $content = Get-Content "lt_out.txt"
        if ($content -match "your url is: (https://.*)") {
            $url = $matches[1]
        }
    }
    $attempts++
}

if ($url) {
    Write-Host "`nSUCCESS: Server shared at -> $url" -ForegroundColor Green
    Write-Host "Access key will be printed in the Backend window." -ForegroundColor Gray
} else {
    Write-Host "`nWARNING: Localtunnel failed to provide a URL within 20s." -ForegroundColor Red
    Write-Host "Check 'lt_out.txt' or the Backend window for errors." -ForegroundColor Gray
}

Write-Host "`nSystems active. Keep the spawned windows open to maintain the share.`n" -ForegroundColor White
