import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ScrambleText } from '@/components/common/ScrambleText'
import { api } from '@/api/client'

/** Render documentary text with section headers scrambled */
function DocumentaryBody({ text }: { text: string }) {
  const lines = text.split('\n')
  return (
    <div className="space-y-2">
      {lines.map((line, i) => {
        const isHeader = line.trim().startsWith('//')
        if (isHeader) {
          return (
            <p key={i} className="font-mono text-xs text-accent/80 tracking-widest uppercase mt-6 first:mt-0">
              <ScrambleText>{line.trim()}</ScrambleText>
            </p>
          )
        }
        if (!line.trim()) return <div key={i} className="h-2" />
        return (
          <p key={i} className="font-mono text-sm text-text-dim leading-relaxed">
            {line}
          </p>
        )
      })}
    </div>
  )
}

export default function Documentary() {
  const { experimentId } = useParams<{ experimentId: string }>()
  const [documentary, setDocumentary] = useState<string | null>(null)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!experimentId) return

    // Check if already cached
    api.getExperiment(experimentId)
      .then((exp) => {
        if (exp.documentary) {
          setDocumentary(exp.documentary)
        } else {
          // Not cached -- generate now
          setGenerating(true)
          api.generateDocumentary(experimentId)
            .then((res) => setDocumentary(res.documentary))
            .catch((err) => setError(err instanceof Error ? err.message : 'Generation failed'))
            .finally(() => setGenerating(false))
        }
      })
      .catch((err) => setError(err instanceof Error ? err.message : 'Experiment not found'))
  }, [experimentId])

  return (
    <div className="flex-1 p-6 max-w-2xl mx-auto space-y-6">

      {/* Header */}
      <div>
        <Link
          to={experimentId ? `/analytics/${experimentId}` : '/gallery'}
          className="font-mono text-[10px] text-text-dim hover:text-accent transition-colors tracking-widest uppercase"
        >
          &larr; Analytics
        </Link>
        <h1 className="font-display font-black tracking-widest text-2xl text-text-primary mt-3">
          <ScrambleText>Documentary</ScrambleText>
        </h1>
        <p className="font-mono text-xs text-text-dim mt-1 tracking-wider">
          <span className="text-accent/60">// </span>
          experiment <span className="text-accent/60">{experimentId}</span>
        </p>
      </div>

      {/* Content */}
      <div className="neural-card p-6 space-y-4">
        {error && (
          <p className="font-mono text-xs text-danger tracking-wider">// error: {error}</p>
        )}
        {generating && (
          <div className="space-y-3">
            <p className="font-mono text-[10px] text-accent/60 tracking-widest uppercase animate-pulse-slow">
              // generating narrative...
            </p>
            <p className="font-mono text-[10px] text-text-dim/40 tracking-wider">
              this may take 10&ndash;20 seconds
            </p>
          </div>
        )}
        {documentary && <DocumentaryBody text={documentary} />}
        {!documentary && !generating && !error && (
          <p className="font-mono text-[10px] text-text-dim/40 tracking-widest animate-pulse-slow">
            // loading...
          </p>
        )}
      </div>

      {/* Footer */}
      {documentary && (
        <p className="font-mono text-[10px] text-text-dim/30 tracking-wider">
          // generated by babel &mdash; cached for future visits
        </p>
      )}
    </div>
  )
}
